Update to how it is supposed to be done nowadays
I was gettng:

```
    gobject.MainLoop().run()
AttributeError: module 'gobject' has no attribute 'MainLoop'
```
and this change fixes it. Not really sure why though:-).